name: Dotnet validate
on: push
jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.403"
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.17.0
      - run: just app/build
